name: Code Quality Check

on:
  - push
  - pull_request

jobs:
  lint-ci:
    runs-on: ubuntu-latest
    name: Install cerberus
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Run install script
        run: |
          python setup.py develop
      - name: pre-commit
        uses: pre-commit/action@v2.0.3
      - uses: BSFishy/pip-action@v1
        with:
          requirements: test-requirements.txt
      - name: Run pre-commit from python
        run: |
          python setup.py develop